name: Daily LLM arXiv digest
sections:
  section 1:
    title: Large Language Model inference optimization
    questions:
      - What are the latest developments around large language inference and quantization?
      - What are the latest developments around large language inference and Mixture of Experts?
      - What are the latest developments around large language inference memory optimization?
  section 2:
    title: Large Language Model training optimization
    questions:
      What are the latest developments around large language models and distributed training across multiple GPUs?
      What are the latest developments around large language models and the tradeoff between model size and number of training tokens?
arxiv-categories: # for a complete descrition of categories see https://arxiv.org/category_taxonomy
  - cs.CL
  - cs.AI
  - cs.IR
  - cs.CV
  - cs.LG
  - cs.NE
